### PR TITLE
Design tweaks

### PR DESCRIPTION
**Pull request by andrealbiac**
Hey! Made a few tweaks to adjust some things that felt a bit off, like:
- Left margin of the page and paddings between elements that felt too cramped. The change is subtle but adding more felt a bit too much
- Text sizes that were too small
- Aligned the `stream-contract` component to the center so the space it's a bit more even on the sides
- Also replaced the logo with a new one that is more legible and doesn't have a subtitle (I think you don't need one in this case? and it was also too small)
- Deleted unused logos

Attatching some pictures of the changes:
Captura de pantalla 2024-10-30 a las 16 58 38
Captura de pantalla 2024-10-30 a las 16 58 18
Captura de pantalla 2024-10-30 a las 16 58 14

Let me know what you think of it!
Thanks

### CODE REVIEW

**Comment by carletex** [comment]
Somethig is breaking on mobile

image

**Comment by andrealbiac** [comment]
Ah true, I forgot to check the responsive 😅 sorry, will update soon

**Comment by andrealbiac** [comment]
Hey! How can you get to that view on localhost? This is the narrowest I can get to see it (and there everything is fine) ->

Captura de pantalla 2024-11-01 a las 12 33 45


Maybe it's another tool or viewport that lets you view it as in mobile?

**Comment by carletex** [comment]
>  (and there everything is fine) 

Yes, but that's not a mobile view, that's more like a tablet.

With Chrome you can use this:

image

which opens this:

image

**Comment by andrealbiac** [comment]
Oh wow thanks! Didn't know that, fixing it asap 🫡

**Comment by andrealbiac** [comment]
So I've been trying everything and can't find how to change this width, it's so weird

It seems like it's some global setting that controls the general layout but it's not in the `globals.tsx`, or the `app.tsx`,also  not any parent container with `max-width`. Also couldn't fix it with the AI help of Cursor editor. 

Maybe we can ask @mac11fish to help with it, or some internal BG reviewers? 
Hope I'm not missing something super obvious

**Comment by carletex** [comment]
Pushed a couple of tweaks to fix the view on mobile https://github.com/BuidlGuidl/media.buidlguidl.com/pull/3/commits/3951383ff7dbe178331c61bde25cfff5d2822f52

The main issue was `w-[500px]` (you were setting a fixed width container that doesn't fit on mobile) + removed the tooltip that wasn't being used (was text-white :D). Also, change "Connect Wallet" to "Connect" to the logo + connect button fix.

**Comment by andrealbiac** [comment]
Oh but it was in the `Stream contract` component! Okay didn't think it could be because of that, thanks!

**Comment by mac11fish** [comment]
sorry guys,
Had my Github account linked to my old email address.
Wasn't getting notifications.
it's switched now

**Pull request merged**
